### ISSUE TITLE
Quicken the configuration process

### ISSUE THREAD

**Issue by davidascher** [carsales/aws-request-signer#2]
As fast as I know, the way to configure this is to click on the dialog, and hit 'save' at every change that needs to be persisted, as even switching from the browser to another window (e.g. to copy a credential) will hide the dialog.   That was a tad frustrating, it'd be nice to have a non-temporary dialog.

**Comment by ghost** [comment]
Apparently it closes by design (not my design, the Chrome team's), and so I could either put the config in a tab/window (ugh) or auto-save (ugh).
