### ISSUE TITLE
Document the instance profile credentials service

### ISSUE THREAD

**Issue by davidascher** [carsales/aws-request-signer#3]
I don't understand what it's for, and the source code refers to a mysterious URL (http://169.254.169.254) which is a tad scary in a credentials-using addon context.

**Comment by ghost** [comment]
Yes it does seem a bit like the extension is sending your data to some mysterious server, but it's all above board - http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html

I could put a link to these docs in the source.
