### ISSUE TITLE
User-defined service & URL

### ISSUE THREAD

**Issue by khuongduybui** [carsales/aws-request-signer#4]
Can you allow users to define our own services and matching URLs?

**Comment by ghost** [comment]
Is there a service missing? Do you want to sign requests to server besides *.amazonaws.com?

**Comment by khuongduybui** [comment]
No, there's no _public_ service missing.
I'm actually working _for_ AWS, and we use SigV4 as a standard for communication between hundreds of internal services. So, the custom matching URLs would be my own hostnames, and the service vendor codes would be internal services :)

**Comment by ghost** [comment]
I'm thinking this would mean moving the list of services and white-listed host names out into an "advanced" config screen. If  you do the work let me know and I'll merge it in, but I don't think I'll get around to it - I don't have anything to test it on...

**Comment by ajmath** [comment]
This is something needed for my team as we're using API gateway with a custom host name.
